# Generated by Django 4.2 on 2023-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название пьесы')),
                ('date', models.TextField(verbose_name='Дата выхода пьесы')),
                ('genre', models.TextField(verbose_name='Жанр пьесы')),
                ('description', models.TextField(verbose_name='Описание пьесы')),
            ],
            options={
                'verbose_name': 'Пьеса',
                'verbose_name_plural': 'Пьесы',
            },
        ),
    ]
