# Generated by Django 4.2 on 2023-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название пьесы')),
                ('date', models.TextField(verbose_name='Дата выхода пьесы')),
                ('genre', models.TextField(verbose_name='Жанр пьесы')),
                ('description_piece', models.TextField(verbose_name='О пьесе')),
                ('description_piece_detailed', models.TextField(verbose_name='Подробнее')),
                ('description_play', models.TextField(verbose_name='О постановке')),
                ('little_known', models.BooleanField(verbose_name='Малоизвестная пьеса')),
            ],
            options={
                'verbose_name': 'Пьеса',
                'verbose_name_plural': 'Пьесы',
            },
        ),
    ]
