# Generated by Django 4.2 on 2023-05-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='id пользователя в телеграме')),
                ('full_name', models.TextField(verbose_name='Имя пользователя')),
                ('username', models.TextField(default='', verbose_name='Юзернейм пользователя при наличии')),
                ('reg_time', models.DateTimeField(verbose_name='Дата регистрации пользователя')),
                ('last_time', models.DateTimeField(verbose_name='Дата последнего действия пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.IntegerField(verbose_name='id сообщения в телеграме')),
                ('msg_name', models.TextField(verbose_name='Название выполненной команды')),
                ('click_time', models.DateTimeField(verbose_name='время и дата выполненной команды')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.user', verbose_name='Пользователь который совершил действие')),
            ],
        ),
    ]
