# Generated by Django 4.2 on 2023-04-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Изображение пьесы'),
        ),
    ]
